travis:
  secure:
    BINSTAR_TOKEN: cOq03Gt+SeTotcg47B+Vng1ela05x1n5sgPzjsr82ji678DBeFj8+cr5ge8qVYeXLct1fa+GX07qk3IM1gXWQKwDpfAyFNxevFQvrkxBEYW6gSo16q7Rme5RPD59WryS5QX8vvj8UelBY2M0ieqmKgYrbD+DFygWA+uTDovPMU4R1sd7tmAn7zU8X9j0mM/ERJZOu89+wOQ0DDB9eMPskwz6A4exutcDgJ0jODcTLt3DuGl6x8xSkbYaEK716wjSD6Kfu2iElVJdnl3n9e50Y8r7yQfSBKUg3HSPu5w7ov84t7CphS2DKRQi8MU046yOCRomhacaFzDIW844JWHflV+eq7xBgEBVvLKs00dkzLvLHAaZ7JJLuq5Fmcvc0inF/SuniSjpEgEBgnkTUS67PQ/XDbIDUpS/CiWO8Sip24YYnsTC5arZMJH+T5LqWt9j+l7zfSG8XYQYX+msIqnj7U06c3S+wgzO/2nszXQHvGl/lgKJR1wPJICGB7MghU9j5nlRzsh07P7jluTAvP/QPuNiC3l1Vi7Mv1vCojUrYfEirjzLeq1Yt/zSZg/MmctpLokGvKJFiF9FCGr1dYBHgQqsjieJ6ULMb2Kz4z5Nbrqo1m0/CYBWnBu2YEbnfXh6ypSn58DLjnvWyiFAprV/xb9A5CCRarQSK0cbxUpab10=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
